apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtmp-server
  namespace: tesis-reid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtmp-server
  template:
    metadata:
      labels:
        app: rtmp-server
    spec:
      containers:
        - name: nginx-rtmp
          image: alfg/nginx-rtmp
          ports:
            - containerPort: 1935
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: config-volume
          configMap:
            name: rtmp-config
