apiVersion: v1
kind: Service
metadata:
  name: rtmp-service
  namespace: tesis-reid
spec:
  type: NodePort  # Usa LoadBalancer si estás en AWS/GCP
  selector:
    app: rtmp-server
  ports:
    - name: rtmp
      port: 1935
      targetPort: 1935
      nodePort: 31935
    - name: http
      port: 8080
      targetPort: 8080
